[tool.commitizen]
version = "0.1.3"
name = "cz_conventional_commits"
version_files = [
    "apps/iperf/main/idf_component.yml",
    "apps/linux-target/main/idf_component.yml",
    "iperf/idf_component.yml",
    "iperf/README.md",
    "iperf-cmd/idf_component.yml",
    "iperf-cmd/README.md",
]
tag_format = "v$version"
version_scheme = "semver"
bump_message = "ci(bump): bump version $current_version → $new_version"
update_changelog_on_bump = false
pre_bump_hooks = [
  "tools/pre_bump_hook.sh"
]
