stages:
  - pre-check
  - build
  - test
  - publish

workflow:
  rules:
    # Disable those non-protected push triggered pipelines
    - if: '$CI_COMMIT_REF_NAME != "main" && $CI_COMMIT_TAG !~ /^v\d+\.\d+(\.\d+)?($|-)/ && $CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1
  IDF_SKIP_CHECK_SUBMODULES: 1
  IDF_CI_BUILD: "1"

include:
  - project: espressif/shared-ci-dangerjs
    ref: master
    file: danger.yaml
run-danger-mr-linter:
  stage: pre-check
  tags:
    - internet

pre_commit_check:
  stage: pre-check
  image: ${GITLAB_DOCKER_REGISTRY}/qa/dockerfiles/qa-python-env:2
  script:
    - pre-commit run --all-files
  tags:
    - build
    - internet

preview_changelog:
  stage: pre-check
  image: ${GITLAB_DOCKER_REGISTRY}/qa/dockerfiles/qa-python-env:2
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 0
  rules:
    - when: on_success
  script:
    - git config --global user.email "temp@example.com"
    - git config --global user.name "Temp"
    - pip install python-gitlab pyYAML commitizen
    - python tools/ci/preview_changelog.py
  tags:
    - host_test


.build_template:
  stage: build
  rules:
    - when: on_success
  artifacts:
    paths:
      - "**/build*/build_log.txt"
      - "**/build*/config/sdkconfig.json"
      # test apps, test on esp32 and esp32c5
      - "apps/test_apps/**/build_*/*.bin"
      - "apps/test_apps/**/build_*/flasher_args.json"
      - "apps/test_apps/**/build_*/config/sdkconfig.json"
      - "apps/test_apps/**/build_*/bootloader/*.bin"
      - "apps/test_apps/**/build_*/partition_table/*.bin"
    when: always
    expire_in: 5 days
  tags:
    - build
    - internet

build_iperf_master:
  extends:
    - .build_template
  image: espressif/idf:latest
  script:
    - pip install idf-build-apps
    - idf-build-apps build --enable-preview-targets ${CI_BUILD_APPS_DISABLE_TARGETS_ARGS} ${CI_BUILD_APPS_IGNORE_WARNING_STRS_ARGS}
    # test weak func
    - grep -a my_report_func apps/test_apps/iperf-cmd/build_esp32_default/iperf.bin

build_iperf:
  extends:
    - .build_template
  image: ${ESP_IMG}
  script:
    - pip install idf-build-apps
    - idf-build-apps build ${CI_BUILD_APPS_IGNORE_WARNING_STRS_ARGS}
  parallel:
    matrix:
      - ESP_IMG: espressif/idf:release-v4.4
      - ESP_IMG: espressif/idf:release-v5.0
      - ESP_IMG: espressif/idf:release-v5.1
      - ESP_IMG: espressif/idf:release-v5.2
      - ESP_IMG: espressif/idf:release-v5.3
      - ESP_IMG: espressif/idf:release-v5.4

# TODO: drop idf v4.x build at iperf v1.0
# idf-build-apps 2.0 do not support python 3.6
build_iperf_v43:
  extends:
    - .build_template
  image: espressif/idf:v4.3.7
  variables:
    LC_ALL: C.UTF-8
  script:
    - pip install idf-build-apps\<2 packaging\<22 idf-component-manager==1.4
    # idf-build-apps 1.x does not support "ignore-warning-strs", ignore all warnings here
    - idf-build-apps build --ignore-warning-str ".+"

.test_job_template:
  stage: test
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "apps/test_apps/**/*"
        - "iperf/**/*.c"
        - "iperf-cmd/**/*.c"
  artifacts:
    when: always
    paths:
      - XUNIT_RESULT.xml
      - pytest_log/
    reports:
      junit: XUNIT_RESULT.xml
    expire_in: 1 week
  script:
    - pip install -r tools/requirements/requirements.pytest.txt
    - pytest apps/test_apps/ --target ${TEST_TARGET} --env ${TEST_ENV}
  variables:
    TEST_TARGET: 'esp32'
    TEST_ENV: generic
  tags:
    - ${TEST_TARGET}
    - ${TEST_ENV}


target_test_master:
  extends:
    - .test_job_template
  needs:
    - job: build_iperf_master
      artifacts: true
  parallel:
    matrix:
      - TEST_TARGET: ['esp32', 'esp32c5']

target_test_releases_4.4:
  extends:
    - .test_job_template
  needs:
    - job: 'build_iperf: [espressif/idf:release-v4.4]'
      artifacts: true
  parallel:
    matrix:
      - TEST_TARGET: 'esp32'

target_test_releases_5.0:
  extends:
    - .test_job_template
  needs:
    - job: 'build_iperf: [espressif/idf:release-v5.0]'
      artifacts: true
  parallel:
    matrix:
      - TEST_TARGET: 'esp32'
