minimum_pre_commit_version: 3.3.0                        # Specifies the minimum version of pre-commit required for this configuration
default_install_hook_types: [pre-commit,commit-msg]      # Default hook types to install if not specified in individual hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude: 'api\.md$'
      - id: end-of-file-fixer
        exclude: 'api\.md$'
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: ['-f=lf']
      - id: double-quote-string-fixer

  - repo: https://github.com/espressif/check-copyright/
    rev: v1.0.3
    hooks:
      - id: check-copyright
        args: ['--config', 'tools/ci/check_copyright_config.yaml']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff # Linter
        args: [--fix, --exit-non-zero-on-fix]
        additional_dependencies: [pyYAML, pytest]
      - id: ruff-format # Formatter

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, pytest]


  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.6.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ["--write-changes"]
        additional_dependencies: [tomli]

  - repo: local
    hooks:
      - id: doxygen-api-md
        name: Doxygen api md
        entry: tools/doxygen_api_md.py
        language: python
        files: 'Doxyfile$|.*\.h$|api\.md'
        pass_filenames: false
        additional_dependencies: [esp-doxybook]
