apps/iperf:
  disable:
    - if: SOC_WIFI_SUPPORTED != 1
      reason: This example app is using wifi connections
    # build specific configuration for only one target
    - if: IDF_TARGET != "esp32" and CONFIG_NAME == "ipv4_only"
    - if: IDF_TARGET != "esp32c3" and CONFIG_NAME == "ipv6_only"
