name: Check pre-commit

on:
  pull_request:

jobs:
  check-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
      - name: Install doxygen (used by doxybook hook)
        run: |
          sudo apt install doxygen
      - uses: pre-commit/action@v3.0.1
