name: Sync Issue Comments to Jira

# This workflow will be triggered when new issue is created
# or a new issue/PR comment is created
on: [issues, issue_comment]

jobs:
  sync_issue_comments_to_jira:
    name: Sync Issue Comments to Jira
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync issue comments to JIRA
        uses: espressif/sync-jira-actions@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_PASS: ${{ secrets.JIRA_PASS }}
          JIRA_PROJECT: MTWJ
          JIRA_COMPONENT: github-issues
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
